typography_spectrum: 0.74819
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.93773
analytics:
  google: null
  facebook: null
  twitter: null
name: Houseplanarchitects.com
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Get Started
    id: 8363f344-9c80-4954-ad99-6801726d509a
    type: content
favicon: null
title: House Plan Architects
purpose: []
