name: Houseplanarchitects.com
favicon: null
layout_spectrum: 0.34206
typography_spectrum: 0.8494144955184311
title: House Plan Architects
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
